config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'products#index'
  resources :categories
  resources :products do
    resources :order_items, only: %i[create update destroy]
  end
  resources :users
  resources :orders

  get 'search', to: 'pages#search'
  get 'search_titles', to: 'pages#search_titles'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :title, presence: true

  def to_param
    "#{id}-#{title}"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items

  enum status: %i[opened closed canceled archived]
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items

  scope :price_range, -> (min, max) { where('price >= ? AND price <= ?', min, max) }

  def self.search(term)
    where("title ILIKE ?", "%#{term}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  helper_method :current_order

  before_action :authenticate_user!, except: %i[index show search search_titles]
  before_action :set_categories

  def set_pagy(obj, items)
    @pagy, @records = pagy(obj, items: items)
  end

  def current_order
    Order.find_or_create_by(user: current_user, status: :opened)
  end

  private

  def set_order_items
    @items = current_order.order_items.order(:id)
  end

  def set_categories
    @categories = Category.all
  end

  def sorting(sort_status)
    case sort_status
    when 'price_asc'
        @products = @products.order(price: :asc)
    when 'price_desc'
        @products = @products.order(price: :desc)
    when 'title_asc'
        @products = @products.order(title: :asc)
    when 'title_desc'
        @products = @products.order(title: :desc)
    end
  end

  def price_filter(min_price, max_price)
    @min_price = min_price
    @max_price = max_price
    max_price = Product.maximum('price') if max_price <= 0
    @products = @products.price_range(min_price, max_price)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = Product.where(category_id: @category.id)
    price_filter(params[:min_price].to_i, params[:max_price].to_i)
    sorting(params[:sort_status])
    set_pagy(@products, 8)
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order_item, only: %i[update destroy]
  before_action :set_order_items, only: %i[update destroy]

  def create
    if current_order.order_items.where(product_id: params[:product_id]).present?
      current_order.order_items.find_by(product_id: params[:product_id]).increment!(:quantity)
    else
      current_order.order_items.create(product_id: params[:product_id], quantity: 1)
    end
    redirect_to current_order
  end

  def update
    case params[:change_quantity]
    when 'increase'
      @order_item.increment!(:quantity)
    when 'decrease'
      @order_item.decrement!(:quantity) if @order_item.quantity > 1
    end
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @order_item.destroy
    @items = current_order.order_items.order(:id)
    respond_to do |format|
      format.js
    end
  end

  private

  def set_order_item
    @order_item = OrderItem.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @items = current_order.order_items.order(:id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def search
    @products = Product.search(params[:query])
    @query = params[:query]
    price_filter(params[:min_price].to_i, params[:max_price].to_i)
    sorting(params[:sort_status])
    set_pagy(@products, 8)
  end

  def search_titles
    @titles = Product.search(params[:term])
    render json: @titles.map(&:title).uniq
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    price_filter(params[:min_price].to_i, params[:max_price].to_i)
    sorting(params[:sort_status])
    set_pagy(@products, 8)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
   include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/show.html.erb
<%= render template: 'products/index' %>

app/views/layouts/_header.html.erb
<div class="container">
  <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
    <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
      <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
    </a>

    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
      <%= link_to 'Home', root_path, class: 'nav-link px-2 text-primary' %>
    </ul>

    <%= form_with url: "/search", method: :get, class: 'col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3', id: 'search' do |form| %>
      <%= form.text_field :query, class: 'form-control form-control-dark', placeholder: 'Search...', 'aria-label': "Search", id: 'autocomplete' %>
    <% end %>

    <div class="text-end">
      <% if user_signed_in? %>
        <%= link_to 'Sign Out', destroy_user_session_path, type: 'button', class: 'btn btn-danger', method: :delete %>
          <% if current_order %>
            <%= link_to 'Cart', order_path(current_order), class: 'btn btn-primary' %>
          <% end %>
        <% else %>
        <%= link_to 'Sign In', new_user_session_path, type: 'button', class: 'btn btn-outline-light me-2' %>
        <%= link_to 'Sign Up', new_user_registration_path, type: 'button', class: 'btn btn-warning' %>
      <% end %>
    </div>
  </div>
</div>

<script>
  $("#autocomplete").autocomplete({
    delay: 500,
    minLength: 2,
    source: '/search_titles',
    select: function(event, ui) {
        $('#autocomplete').val(ui.item.label);
        $('#search').submit();
    }
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "jquery-ui.min", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "jquery-ui.min", "data-turbo-track": "reload" %>
  </head>

  <body>
    <header class="p-3 bg-dark text-white">
      <%= render 'layouts/header' %>
    </header>
    <% if notice || alert %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
    <main>
      <%= yield %>
    </main>
    <footer>
    </footer>
  </body>
</html>

app/views/order_items/_order_item.html.erb
<div id="order_item-<%= item.id %>" class="">
  <p>Title: <%= item.product.title %></p>
  <p>Description: <%= item.product.description %></p>
  <p>Price per/1: <%= item.product.price %></p>
  <p>Total: <%= item.product.price * item.quantity %></p>
  <div class="d-flex">
    <div class="">
      <%= button_to '-', product_order_item_path(item.product, item), method: :patch, class: 'btn btn-danger', params: { change_quantity: :decrease }, remote: true %>
    </div>
    <div id="quantity-<%= item.id %>" class="justify-content-center btn btn-warning">
      <%= item.quantity %>
    </div>
    <div class="">
      <%= button_to '+', product_order_item_path(item.product, item), method: :patch, class: 'btn btn-success', params: { change_quantity: :increase }, remote: true %>
    </div>
    <div id="delete" class="">
      <%= button_to 'Delete', product_order_item_path(item.product, item), id: 'delete', method: :delete, remote: true, class: 'btn btn-danger' %>
    </div>
  </div>
  <hr>
</div>

app/views/order_items/destroy.js.erb
$( "#order_item-<%= @order_item.id %>" ).hide();
document.querySelector('#total-price').innerHTML = "Total price: <%= j @items.each.sum { |i| i.product.price * i.quantity } %> UAH";

app/views/order_items/update.js.erb
document.querySelector('#order_item-<%= @order_item.id %>').innerHTML = "<%= j render 'order_items/order_item', item: @order_item %>";
document.querySelector('#total-price').innerHTML = "Total price: <%= j @items.each.sum { |i| i.product.price * i.quantity } %> UAH";

app/views/orders/show.html.erb
<% if @items.size > 0 %>
  <% @items.each do |item| %>
    <%= render 'order_items/order_item', item: item %>
  <% end %>
  <hr>
  <div id="total-price" class="">
    Total price: <%= @items.each.sum { |i| i.product.price * i.quantity } %> UAH
  </div>
<% else %>
  Cart is Empty
<% end %>

app/views/pages/search.html.erb
<h1>Search Result</h1>

<%= render template: 'products/index' %>

app/views/products/_product.html.erb
<div class="col-3 pt-5">
  <div class="card" style="width: 18rem;">
    <%= image_tag 'no-img-200x200.jpg', class: "bd-placeholder-img card-img-top img-fluid", alt: '<image>' %>
    <div class="card-body">
      <h5 class="card-title"><%= product.title %></h5>
      <p class="card-text"><%= product.description.truncate(30) %></p>
      <p class="card-text"><%= product.price %></p>
      <%= link_to 'Show', product %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="row">
  <div class="col-sm-3 col-12">
    <nav class="nav nav-pills flex-column">
      <% @categories.each do |category| %>
          <%= link_to(category.title, category, class: "nav-link #{'active' if current_page?(category)}" ) %>
      <% end %>
    </nav>
  </div>
  <div class="col-sm-9 col-12">
    <br>
    <% if @records.size > 0 %>
    <%= render 'shared/sort_products' %>
    <div class="row products">
      <%= render @records %>
      <% else %>
      <h2>Not Found</h2>
    </div>
    <% end %>
    <br>
    <div class="nav-bar pagination">
      <% if @pagy.pages > 1 %>
      <%== pagy_bootstrap_nav(@pagy) %>
      <%== pagy_info(@pagy) %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <p><%= @product.title %></p>
  <p><%= @product.description %></p>
  <p><%= @product.price %></p>
  <p><%= button_to 'Buy', product_order_items_path(@product), class: 'btn btn-success' %></p>
</div>

app/views/shared/_sort_products.html.erb
<div class="d-flex">
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
      Сортировать
    </button>
    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
      <li><%= button_to 'От дешевых к дорогим', '#', method: :get, params: {sort_status: :price_asc, query: @query, min_price: @min_price, max_price: @max_price}, class: 'dropdown-item' %></li>
      <li><%= button_to 'От дорогих к дешевым', '#', method: :get, params: {sort_status: :price_desc, query: @query, min_price: @min_price, max_price: @max_price}, class: 'dropdown-item' %></li>
      <li><%= button_to 'От А до Я', '#', method: :get, params: {sort_status: :title_asc, query: @query, min_price: @min_price, max_price: @max_price}, class: 'dropdown-item' %></li>
      <li><%= button_to 'От Я до А', '#', method: :get, params: {sort_status: :title_desc, query: @query, min_price: @min_price, max_price: @max_price}, class: 'dropdown-item' %></li>
    </ul>
    <div class="price_filter">
      <%= form_with(url: '#', method: :get) do |f| %>
        <%= f.number_field :min_price, placeholder: 'from' %>
        <%= f.number_field :max_price, placeholder: 'to' %>
        <%= f.hidden_field :query, value: @query %>
        <%= f.submit 'Filter' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<h1>Users#profile</h1>
<p>Find me in app/views/users/profile.html.erb</p>